config/routes.rb
Rubbletorubyblog::Application.routes.draw do

  root 'blogposts#index'

  resources :about

  get 'info', :to =>'blogposts#info'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController

	def index
	end

	def info
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/views/blogposts/index.html.erb
<div class="blogtitle col-xs-12">
Rubble to Ruby
</div>

<div class="blogbox col-xs-8 col-xs-offset-2">
	<h2>29th November 2015</h2>
		<p>Start theFirehoseProject.</p>
	<br />
	<h2>10th December 2015</h2>
		<p>Test Post.</p>
	<h2>10th December 2015</h2>
		<p>Test Post.</p>
	<h2>10th December 2015</h2>
		<p>Test Post.</p>
	<h2>10th December 2015</h2>
		<p>Test Post.</p>
	<h2>10th December 2015</h2>
		<p>Test Post.</p>
	<br />
</div>

<div class="footer">
	<div class="container">
		<div class="col-xs-6 about">
			<%= link_to 'About', info_path %>
		</div>
		<div class="col-xs-6">
			<a href="https://github.com/VictoriaBrouard" target="blank">
			<%=image_tag("GH.png") %> </a>
			<a href="https://www.linkedin.com/in/victoria-brouard-5397b13b" target="blank">
			<%=image_tag("LI.png") %> </a>
		</div>
	</div>
</div>

app/views/blogposts/info.html.erb
<div class="col-xs-10 col-xs-offset-1">
	<h1>About Victoria</h1>

	<p>
		BLURB
	</p>
</div>

<div class="col-xs-12 about">
	<%= link_to 'Back to Blog', root_path %><br />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubbletorubyblog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>